# Site settings
title: Arde
email: arde@proyectoarde.org
url: https://pdaire.github.io #royectoarde.org
baseurl: /arde-homepage
description: "Archivo de Procesos Creativos"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#3f3f3f'
  links: '#219ab3'

# Footer settings
footer: © Proyecto Arde /

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/proyectoarde
  - title: facebook
    url: https://www.facebook.com/archivoarde

# Build settings
markdown: kramdown
permalink: pretty
