# Site settings
title: Arde
email: arde@proyectoarde.org
url: https://pdaire.github.io #royectoarde.org
description: "Archivo de procesos creativos"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#3f3f3f'
  links: '#fff'

# Footer settings
footer: Proyecto Arde

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://instagram.com/proyectoarde
  - title: facebook
    url: https://www.facebook.com/archivoarde

# Build settings
markdown: kramdown
permalink: pretty
